module.exports = {
	SEARCH_IGDB: 'SEARCH_IGDB',
	IGDB_SEARCH_SUCCESS: 'IGDB_SEARCH_SUCCESS',
	IGDB_SEARCH_FAILURE: 'IGDB_SEARCH_FAILURE',
	UPDATE_CURRENT_SEARCH_SETTINGS: 'UPDATE_CURRENT_SEARCH_SETTINGS',
};